version: "2"
services:
  dev:
    image: davidbanham/docker-golang-gin
    env_file: ./.env
    environment:
      - PORT=3001
      - AUTH_SECRET=loltestsecret
      - NOTIFY_EMAIL_FROM=test@example.com
      - NOTIFY_SMS_FROM=test
      - NOTIFY_EMAIL_PROVIDER=amazon
      - NOTIFY_SMS_PROVIDER=amazon
      - DISABLE_AUTH=true
    command: gin
    ports:
     - "3000:3000"
    volumes:
      - .:/go/src/github.com/davidbanham/notify
      - .:/go/src/app
  prodtest:
    build: .
    env_file: ./.env
    environment:
      - PORT=3001
    ports:
     - "3001:3000"
