version: "2"
services:
  dev:
    image: davidbanham/docker-golang-gin
    env_file: ./.env
    environment:
      - PORT=3001
    command: gin
    ports:
     - "3000:3000"
    volumes:
      - .:/go/src/github.com/davidbanham/notify
      - .:/go/src/app
  prodtest:
    build: .
    env_file: ./.env
    environment:
      - PORT=3001
    ports:
     - "3001:3000"
